"""
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
"""


def even_fibonacci(top):
    
    top = 4000000
    total = 0
    a, b = 0, 1

    while total < top:
        term = a + b
        if term % 2 == 0:
            total = total + term
        a = b
        b = term
        
    return total
    
if __name__ == '__main__':
    print even_fibonacci(4000000)
